services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    volumes:
      - ./app:/app 
    ports:
      - "3001:3001"  
    environment:
      - PYTHONUNBUFFERED=1  
    command: ["python", "app.py"]

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - minio_data:/data
    command: server --address ":9001" --console-address ":9000" /data
    restart: always


volumes:
  minio_data: